"""Facade and top-level entry points for live rendering."""

import json
from pathlib import Path
from typing import Literal
from pydantic import BaseModel, ConfigDict

from gitgeist.render.abstract_renderer import generate_abstract_simulation
from gitgeist.render.character_renderer import generate_character_simulation
from gitgeist.render.html_template import generate_live_html
from gitgeist.schemas.live_state import LiveSimulationState
from gitgeist.schemas.visual_latent import VisualLatentProfile


class LiveRenderArtifacts(BaseModel):
    """Artifact bundle generated by live rendering."""

    model_config = ConfigDict(frozen=True, arbitrary_types_allowed=True)

    state: LiveSimulationState
    html_content: str
    state_json: str
    html_path: Path | None = None
    json_path: Path | None = None


def render_live(
    profile: VisualLatentProfile,
    mode: Literal["abstract", "character"] = "abstract",
    repository_name: str | None = None,
    output_dir: Path | str | None = None,
) -> LiveRenderArtifacts:
    """Render a live interactive preview and simulation state from a VisualLatentProfile.

    Args:
        profile: VisualLatentProfile instance to render.
        mode: Representation mode, either 'abstract' or 'character' (default 'abstract').
        repository_name: Optional display name for the repository.
        output_dir: Optional directory path to write 'live-preview.html' and 'live-state.json'.

    Returns:
        LiveRenderArtifacts bundle with HTML, JSON and optional written file paths.

    Raises:
        TypeError: If profile is not an instance of VisualLatentProfile.
        ValueError: If mode is not 'abstract' or 'character'.
    """
    if not isinstance(profile, VisualLatentProfile):
        raise TypeError(f"Expected VisualLatentProfile, got {type(profile).__name__}")

    if mode == "abstract":
        state = generate_abstract_simulation(profile, repository_name=repository_name)
    elif mode == "character":
        state = generate_character_simulation(profile, repository_name=repository_name)
    else:
        raise ValueError(f"Unsupported representation mode: {mode!r}. Must be 'abstract' or 'character'.")

    html_content = generate_live_html(state)
    state_json = state.model_dump_json(indent=2)

    html_path: Path | None = None
    json_path: Path | None = None

    if output_dir is not None:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        html_path = out / "live-preview.html"
        json_path = out / "live-state.json"
        html_path.write_text(html_content, encoding="utf-8")
        json_path.write_text(state_json, encoding="utf-8")

    return LiveRenderArtifacts(
        state=state,
        html_content=html_content,
        state_json=state_json,
        html_path=html_path,
        json_path=json_path,
    )
