"""Facade and top-level entry points for live and prompt rendering."""

import json
from pathlib import Path
from typing import Literal
from pydantic import BaseModel, ConfigDict

from gitgeist.render.abstract_renderer import generate_abstract_simulation
from gitgeist.render.character_renderer import generate_character_simulation
from gitgeist.render.html_template import generate_live_html
from gitgeist.render.image_backend import (
    FakeImageBackend,
    ImageGenerationBackend,
    detect_media_type,
    normalize_to_png,
)
from gitgeist.render.prompt_composer import RepresentationMode, compose_prompt
from gitgeist.schemas.live_state import LiveSimulationState
from gitgeist.schemas.visual_latent import VisualLatentProfile
from gitgeist.schemas.emotional import EmotionalState

PORTRAIT_FILENAMES = {"png": "portrait.png", "jpeg": "portrait.jpg", "webp": "portrait.webp"}
ImageFormat = Literal["native", "png"]


class LiveRenderArtifacts(BaseModel):
    """Artifact bundle generated by live rendering."""

    model_config = ConfigDict(frozen=True, arbitrary_types_allowed=True)

    state: LiveSimulationState
    html_content: str
    state_json: str
    html_path: Path | None = None
    json_path: Path | None = None


def render_live(
    profile: VisualLatentProfile,
    mode: Literal["abstract", "character"] = "abstract",
    repository_name: str | None = None,
    output_dir: Path | str | None = None,
) -> LiveRenderArtifacts:
    """Render a live interactive preview and simulation state from a VisualLatentProfile.

    Args:
        profile: VisualLatentProfile instance to render.
        mode: Representation mode, either 'abstract' or 'character' (default 'abstract').
        repository_name: Optional display name for the repository.
        output_dir: Optional directory path to write 'live-preview.html' and 'live-state.json'.

    Returns:
        LiveRenderArtifacts bundle with HTML, JSON and optional written file paths.

    Raises:
        TypeError: If profile is not an instance of VisualLatentProfile.
        ValueError: If mode is not 'abstract' or 'character'.
    """
    if not isinstance(profile, VisualLatentProfile):
        raise TypeError(f"Expected VisualLatentProfile, got {type(profile).__name__}")

    if mode == "abstract":
        state = generate_abstract_simulation(profile, repository_name=repository_name)
    elif mode == "character":
        state = generate_character_simulation(profile, repository_name=repository_name)
    else:
        raise ValueError(f"Unsupported representation mode: {mode!r}. Must be 'abstract' or 'character'.")

    html_content = generate_live_html(state)
    state_json = state.model_dump_json(indent=2)

    html_path: Path | None = None
    json_path: Path | None = None

    if output_dir is not None:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        html_path = out / "live-preview.html"
        json_path = out / "live-state.json"
        html_path.write_text(html_content, encoding="utf-8")
        json_path.write_text(state_json, encoding="utf-8")

    return LiveRenderArtifacts(
        state=state,
        html_content=html_content,
        state_json=state_json,
        html_path=html_path,
        json_path=json_path,
    )


class PromptRenderArtifacts(BaseModel):
    """Artifact bundle generated by prompt rendering."""

    model_config = ConfigDict(frozen=True)

    prompt_text: str
    image_bytes: bytes | None = None
    media_type: str | None = None
    prompt_path: Path | None = None
    image_path: Path | None = None


def render_prompt(
    emotional_state: EmotionalState,
    profile: VisualLatentProfile,
    mode: RepresentationMode = "abstract",
    repository_name: str | None = None,
    backend: ImageGenerationBackend | None = None,
    output_dir: Path | str | None = None,
    image_format: ImageFormat = "native",
) -> PromptRenderArtifacts:
    """Compose a prompt, generate a portrait image and optionally write artifacts.

    Args:
        emotional_state: EmotionalState instance to describe in the prompt.
        profile: VisualLatentProfile instance to describe in the prompt.
        mode: Representation mode, either 'abstract' or 'character' (default 'abstract').
        repository_name: Optional display name for the repository.
        backend: ImageGenerationBackend used to generate the image; defaults to FakeImageBackend.
        output_dir: Optional directory path to write 'prompt.txt' and a portrait file named
            after the detected media type ('portrait.png', 'portrait.jpg', 'portrait.webp').
        image_format: 'native' keeps the detected format; 'png' converts non-PNG output
            to PNG through Pillow.

    Returns:
        PromptRenderArtifacts bundle with prompt text, image bytes, the detected media
        type and optional written paths.

    Raises:
        TypeError: If emotional_state or profile is of unexpected type.
        ValueError: If mode is not 'abstract' or 'character', image_format is unknown,
            the image bytes have an unrecognized format, or normalization is requested
            without Pillow.
    """
    if not isinstance(emotional_state, EmotionalState):
        raise TypeError(f"Expected EmotionalState, got {type(emotional_state).__name__}")
    if not isinstance(profile, VisualLatentProfile):
        raise TypeError(f"Expected VisualLatentProfile, got {type(profile).__name__}")
    if image_format not in ("native", "png"):
        raise ValueError(f"Unsupported image format: {image_format!r}. Must be 'native' or 'png'.")

    prompt_text = compose_prompt(emotional_state, profile, mode=mode, repository_name=repository_name)
    selected_backend = backend if backend is not None else FakeImageBackend()
    generated = selected_backend.generate_image(prompt_text)
    image_bytes = generated.image_bytes
    media_type = detect_media_type(image_bytes)

    if image_format == "png" and media_type != "png":
        image_bytes = normalize_to_png(image_bytes)
        media_type = "png"

    prompt_path: Path | None = None
    image_path: Path | None = None

    if output_dir is not None:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        prompt_path = out / "prompt.txt"
        image_path = out / PORTRAIT_FILENAMES[media_type]
        prompt_path.write_text(prompt_text, encoding="utf-8")
        image_path.write_bytes(image_bytes)

    return PromptRenderArtifacts(
        prompt_text=prompt_text,
        image_bytes=image_bytes,
        media_type=media_type,
        prompt_path=prompt_path,
        image_path=image_path,
    )
