"""Deterministic summary and why-this-look explanations for repository portraits.

Produces the required artifacts ``summary.md`` and ``profile.json`` (product
specification section 23) and the section 27 explainability view: emotional
state, visual latent profile, top contributing repository signals, top JEV
sensors and a textual explanation of why the portrait looks the way it does.

The attribution table ``_AXIS_SCORE_WEIGHTS`` mirrors the emotional-to-axis
weights in ``gitgeist.mapping.axes`` for explanatory purposes only; the
mapping module stays the single source of behavior.
"""

from __future__ import annotations

import json
from pathlib import Path

from pydantic import BaseModel, ConfigDict

from gitgeist.schemas.emotional import EmotionalNouls, EmotionalState
from gitgeist.schemas.features import RepositoryFeatures
from gitgeist.schemas.visual_latent import VisualLatentProfile

_SCORE_NAMES = (
    "coherence",
    "maturity",
    "volatility",
    "fragility",
    "novelty",
    "discipline",
    "tension",
    "chaos",
    "identity_strength",
    "internal_conflict",
)

_AXIS_NAMES = (
    "form_complexity",
    "symmetry",
    "fragmentation",
    "tension_curvature",
    "texture_density",
    "luminosity",
    "contrast",
    "sharpness",
    "visual_rhythm",
    "compositional_balance",
    "biological_vs_mechanical",
    "ornamental_load",
    "opacity",
    "layering",
)

_LOW_THRESHOLD = 0.33
_MEDIUM_THRESHOLD = 0.66
_TOP_AXES_COUNT = 3
_TOP_SENSORS_COUNT = 5
_MAX_ATTRIBUTIONS = 3
_MIN_CONTRIBUTION = 0.03

_NEUTRAL_DISTANCE = 0.5

# Literal look vocabulary per axis: (high_value_word, low_value_word).
_LOOK_WORDS: dict[str, tuple[str, str]] = {
    "form_complexity": ("complex", "simple"),
    "symmetry": ("symmetrical", "asymmetrical"),
    "fragmentation": ("fragmented", "cohesive"),
    "tension_curvature": ("tense", "relaxed"),
    "texture_density": ("densely textured", "smooth"),
    "luminosity": ("luminous", "dark"),
    "contrast": ("high-contrast", "low-contrast"),
    "sharpness": ("sharp", "soft"),
    "visual_rhythm": ("rhythmic", "flat"),
    "compositional_balance": ("balanced", "unbalanced"),
    "biological_vs_mechanical": ("mechanical", "organic"),
    "ornamental_load": ("ornate", "plain"),
    "opacity": ("opaque", "translucent"),
    "layering": ("layered", "unlayered"),
}

# Explanatory mirror of the score weights in gitgeist.mapping.axes
# (nouls and choices contributions are intentionally not attributed).
_AXIS_SCORE_WEIGHTS: dict[str, tuple[tuple[str, float], ...]] = {
    "form_complexity": (("novelty", 0.35), ("internal_conflict", 0.25)),
    "symmetry": (("discipline", 0.4), ("coherence", 0.35), ("chaos", -0.45)),
    "fragmentation": (("chaos", 0.45), ("fragility", 0.25), ("coherence", -0.35)),
    "tension_curvature": (("tension", 0.45), ("internal_conflict", 0.3), ("volatility", 0.25)),
    "texture_density": (("tension", 0.3), ("volatility", 0.25)),
    "luminosity": (("novelty", 0.25),),
    "contrast": (("identity_strength", 0.35), ("tension", 0.3)),
    "sharpness": (("discipline", 0.35), ("maturity", 0.3)),
    "visual_rhythm": (("discipline", 0.4), ("coherence", 0.35), ("chaos", -0.45)),
    "compositional_balance": (("coherence", 0.4), ("maturity", 0.35), ("volatility", -0.3)),
    "biological_vs_mechanical": (("discipline", 0.4), ("maturity", 0.3), ("novelty", -0.25)),
    "ornamental_load": (("novelty", 0.3), ("discipline", -0.35)),
    "opacity": (("maturity", 0.35), ("identity_strength", 0.35), ("fragility", -0.3)),
    "layering": (("maturity", 0.35), ("coherence", 0.3)),
}


class ExplanationArtifacts(BaseModel):
    """Artifact bundle generated by the explainability layer."""

    model_config = ConfigDict(frozen=True)

    summary_md: str
    why_this_look: tuple[str, ...]
    profile_json: str
    summary_path: Path | None = None
    profile_path: Path | None = None


def _qualifier(value: float) -> str:
    if value <= _LOW_THRESHOLD:
        return "low"
    if value <= _MEDIUM_THRESHOLD:
        return "medium"
    return "high"


def _validate_inputs(
    features: RepositoryFeatures,
    emotional_state: EmotionalState,
    profile: VisualLatentProfile,
) -> None:
    if not isinstance(features, RepositoryFeatures):
        raise TypeError(f"Expected RepositoryFeatures, got {type(features).__name__}")
    if not isinstance(emotional_state, EmotionalState):
        raise TypeError(f"Expected EmotionalState, got {type(emotional_state).__name__}")
    if not isinstance(profile, VisualLatentProfile):
        raise TypeError(f"Expected VisualLatentProfile, got {type(profile).__name__}")


def _top_axes(profile: VisualLatentProfile) -> list[str]:
    entries = [(name, abs(getattr(profile.axes, name) - _NEUTRAL_DISTANCE)) for name in _AXIS_NAMES]
    ranked = sorted(entries, key=lambda item: (-item[1], item[0]))
    return [name for name, _ in ranked[:_TOP_AXES_COUNT]]


def _top_sensors(state: EmotionalState) -> list[str]:
    entries = [(name, abs(getattr(state.scores, name) - _NEUTRAL_DISTANCE)) for name in _SCORE_NAMES]
    ranked = sorted(entries, key=lambda item: (-item[1], item[0]))
    return [name for name, _ in ranked[:_TOP_SENSORS_COUNT]]


def _look_phrase(axis_name: str, value: float) -> str:
    high_word, low_word = _LOOK_WORDS[axis_name]
    if value > _MEDIUM_THRESHOLD:
        return high_word
    if value <= _LOW_THRESHOLD:
        return low_word
    return f"moderately {high_word}"


def _why_headline(profile: VisualLatentProfile) -> str:
    words = [_look_phrase(name, getattr(profile.axes, name)) for name in _top_axes(profile)]
    joined = ", ".join(words[:-1]) + " and " + words[-1]
    return f"Why does this portrait look {joined}?"


def _axis_attributions(axis_name: str, state: EmotionalState) -> list[str]:
    entries: list[tuple[str, float, float]] = []
    for score_name, weight in _AXIS_SCORE_WEIGHTS[axis_name]:
        value = getattr(state.scores, score_name)
        contribution = weight * (value - _NEUTRAL_DISTANCE)
        if abs(contribution) < _MIN_CONTRIBUTION:
            continue
        entries.append((score_name, value, contribution))
    entries.sort(key=lambda item: (-abs(item[2]), item[0]))

    if not entries:
        return [f"no single dominant emotional driver behind {axis_name}"]

    bullets: list[str] = []
    for score_name, value, contribution in entries[:_MAX_ATTRIBUTIONS]:
        direction = "raises" if contribution > 0 else "lowers"
        bullets.append(f"{_qualifier(value)} {score_name} ({direction} {axis_name})")
    return bullets


def _why_this_look(state: EmotionalState, profile: VisualLatentProfile) -> tuple[str, ...]:
    lines: list[str] = [_why_headline(profile)]
    for axis_name in _top_axes(profile):
        lines.extend(_axis_attributions(axis_name, state))
    return tuple(lines)


def _overview_lines(features: RepositoryFeatures) -> list[str]:
    static = features.static
    history = features.history
    docs = features.docs

    lines = [
        f"- files: {static.file_count} in {static.directory_count} directories "
        f"(max depth {static.max_directory_depth})"
    ]
    if static.languages:
        top_languages = sorted(static.languages.items(), key=lambda item: (-item[1], item[0]))[:3]
        listing = ", ".join(f"{name} ({count})" for name, count in top_languages)
        lines.append(f"- languages: {listing}")
    else:
        lines.append("- languages: none detected")
    lines.append(
        f"- size: {static.total_size_bytes} bytes "
        f"(average {static.avg_file_size_bytes:.1f} bytes per file)"
    )
    if history.is_git_repo:
        lines.append(
            f"- git: {history.commit_count} commits by {history.unique_authors_count} authors, "
            f"age {history.repository_age_days} days, "
            f"velocity {history.velocity:.2f} commits/day"
        )
        lines.append(f"- churn: +{history.total_lines_added} -{history.total_lines_deleted} lines")
    else:
        lines.append("- git: no history available")

    hygiene: list[str] = []
    if static.has_tests:
        hygiene.append("tests")
    if static.has_ci:
        hygiene.append("CI")
    if docs.has_readme:
        hygiene.append("README")
    if static.has_documentation:
        hygiene.append("documentation")
    if docs.license_type:
        hygiene.append(f"license: {docs.license_type}")
    lines.append("- hygiene: " + (", ".join(hygiene) if hygiene else "none detected"))

    if static.todo_count > 0:
        lines.append(f"- TODO/FIXME markers: {static.todo_count}")
    if history.hotspots:
        top_hotspots = sorted(history.hotspots, key=lambda item: (-item.change_count, item.path))[:3]
        listing = ", ".join(f"{item.path} ({item.change_count})" for item in top_hotspots)
        lines.append(f"- hotspots: {listing}")
    return lines


def _signals_for_score(score_name: str, features: RepositoryFeatures) -> list[str]:
    static = features.static
    history = features.history
    docs = features.docs

    signals: list[str] = []

    if score_name == "coherence":
        if docs.has_readme:
            signals.append("README present")
        if static.has_documentation:
            signals.append("documentation directory present")
        if static.languages:
            total = sum(static.languages.values())
            dominant_language, dominant_count = sorted(
                static.languages.items(), key=lambda item: (-item[1], item[0])
            )[0]
            if total > 0 and dominant_count / total >= 0.6:
                signals.append(f"single dominant language: {dominant_language}")
        if static.directory_count > 0:
            signals.append("modular directory layout")
    elif score_name == "maturity":
        if history.is_git_repo and history.repository_age_days >= 180:
            signals.append(f"long history ({history.repository_age_days} days)")
        if history.is_git_repo and history.commit_count >= 30:
            signals.append(f"substantial commit history ({history.commit_count} commits)")
        if static.has_tests:
            signals.append("test suite present")
        if docs.license_type:
            signals.append(f"license declared: {docs.license_type}")
        if static.has_ci:
            signals.append("CI configuration present")
    elif score_name == "volatility":
        if not history.is_git_repo:
            signals.append("no git history baseline")
        else:
            if history.velocity >= 2.0:
                signals.append(f"high commit velocity ({history.velocity:.2f} commits/day)")
            if history.total_lines_added + history.total_lines_deleted > 0:
                signals.append(
                    f"large code churn (+{history.total_lines_added} "
                    f"-{history.total_lines_deleted} lines)"
                )
    elif score_name == "fragility":
        if (
            history.is_git_repo
            and history.commit_count > 0
            and history.hotspots
            and history.hotspots[0].change_count / history.commit_count >= 0.3
        ):
            signals.append(f"changes concentrated in {history.hotspots[0].path}")
        if not static.has_tests:
            signals.append("no test suite")
        if static.todo_count >= 5:
            signals.append(f"{static.todo_count} TODO/FIXME markers")
    elif score_name == "novelty":
        if not history.is_git_repo:
            signals.append("no git history baseline")
        else:
            if history.repository_age_days < 90:
                signals.append(f"young history ({history.repository_age_days} days)")
            if history.commit_count < 10:
                signals.append(f"few commits ({history.commit_count})")
    elif score_name == "discipline":
        if static.has_ci:
            signals.append("CI configuration present")
        if static.has_tests:
            signals.append("test suite present")
        if docs.has_readme:
            signals.append("README present")
        if docs.license_type:
            signals.append(f"license declared: {docs.license_type}")
        if static.directory_count > 0:
            signals.append("modular directory layout")
        if static.todo_count == 0:
            signals.append("no TODO/FIXME markers")
    elif score_name == "tension":
        if (
            history.is_git_repo
            and history.commit_count > 0
            and history.hotspots
            and history.hotspots[0].change_count / history.commit_count >= 0.3
        ):
            signals.append(f"repeated changes in {history.hotspots[0].path}")
        if history.is_git_repo and history.velocity >= 1.0:
            signals.append(f"active pace ({history.velocity:.2f} commits/day)")
        if history.unique_authors_count > 1:
            signals.append(f"{history.unique_authors_count} contributors")
    elif score_name == "chaos":
        if static.directory_count == 0 and static.file_count > 3:
            signals.append("flat file layout")
        if not static.has_tests:
            signals.append("no test suite")
        if not docs.has_readme:
            signals.append("no README")
        if not static.has_ci:
            signals.append("no CI configuration")
        if static.todo_count >= 5:
            signals.append(f"{static.todo_count} TODO/FIXME markers")
    elif score_name == "identity_strength":
        if docs.has_readme:
            if docs.readme_length_chars >= 500:
                signals.append("detailed README")
            else:
                signals.append("README present")
        if docs.license_type:
            signals.append(f"license declared: {docs.license_type}")
        if static.languages:
            signals.append(f"declared languages: {len(static.languages)}")
        if history.is_git_repo and history.commit_count >= 10:
            signals.append(f"established commit history ({history.commit_count} commits)")
    elif score_name == "internal_conflict":
        if not static.has_tests and history.is_git_repo and history.velocity > 2.0:
            signals.append("rapid changes without tests")
        if len(static.languages) > 3:
            signals.append(f"many coexisting languages ({len(static.languages)})")
        if static.todo_count > 5 and static.has_ci:
            signals.append("TODO debt despite CI")

    if not signals:
        return ["no distinguishing repository signals"]
    return signals[:_MAX_ATTRIBUTIONS]


def _emotional_state_lines(state: EmotionalState) -> list[str]:
    lines = [
        f"- {name}: {_qualifier(getattr(state.scores, name))} ({getattr(state.scores, name):.2f})"
        for name in _SCORE_NAMES
    ]
    active_nouls = [
        field for field in EmotionalNouls.model_fields if getattr(state.nouls, field)
    ]
    lines.append("- nouls: " + (", ".join(active_nouls) if active_nouls else "none active"))
    for label, distribution in (
        ("temperament", state.choices.temperament),
        ("visual tone", state.choices.visual_tone),
        ("energy profile", state.choices.energy_profile),
    ):
        lines.append(
            f"- {label}: dominant {distribution.dominant} ({distribution.weights[distribution.dominant]:.2f})"
        )
    return lines


def _visual_latent_lines(profile: VisualLatentProfile) -> list[str]:
    lines = [
        f"- {name}: {_qualifier(getattr(profile.axes, name))} ({getattr(profile.axes, name):.2f})"
        for name in _AXIS_NAMES
    ]
    lines.append(
        f"- dominant material: {profile.materiality.dominant} "
        f"({profile.materiality.weights[profile.materiality.dominant]:.2f})"
    )
    if profile.dominant_features:
        lines.append(f"- dominant features: {', '.join(profile.dominant_features)}")
    return lines


def _compose_summary_md(
    features: RepositoryFeatures,
    state: EmotionalState,
    profile: VisualLatentProfile,
    repository_name: str | None,
    why_lines: tuple[str, ...],
) -> str:
    title = f"# Repository Portrait: {repository_name}" if repository_name else "# Repository Portrait"

    top_sensors = _top_sensors(state)

    why_block = [f"## {why_lines[0]}"]
    why_block.extend(f"- {line}" for line in why_lines[1:])

    sensors_block = ["## Top JEV sensors"]
    sensors_block.extend(
        f"- {name}: {_qualifier(getattr(state.scores, name))} ({getattr(state.scores, name):.2f})"
        for name in top_sensors
    )

    signals_block = ["## Top contributing repository signals"]
    signals_block.extend(
        f"- {name}: " + "; ".join(_signals_for_score(name, features)) for name in top_sensors
    )

    blocks = [
        [title],
        ["## Repository overview", *_overview_lines(features)],
        ["## Emotional state", *_emotional_state_lines(state)],
        ["## Visual latent profile", *_visual_latent_lines(profile)],
        why_block,
        sensors_block,
        signals_block,
    ]
    return "\n\n".join("\n".join(block) for block in blocks) + "\n"


def _serialize_profiles(
    features: RepositoryFeatures,
    state: EmotionalState,
    profile: VisualLatentProfile,
) -> str:
    payload = {
        "emotional_state": state.model_dump(mode="json"),
        "repository": features.model_dump(mode="json"),
        "visual_latent": profile.model_dump(mode="json"),
    }
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def explain(
    features: RepositoryFeatures,
    emotional_state: EmotionalState,
    profile: VisualLatentProfile,
    repository_name: str | None = None,
    output_dir: Path | str | None = None,
) -> ExplanationArtifacts:
    """Produce the deterministic summary and why-this-look explanation.

    Args:
        features: RepositoryFeatures instance (Layer 1).
        emotional_state: EmotionalState instance (Layer 2).
        profile: VisualLatentProfile instance (Layer 3).
        repository_name: Optional repository display name.
        output_dir: Optional directory path to write 'summary.md' and 'profile.json'.

    Returns:
        ExplanationArtifacts bundle with summary text, why-this-look lines,
        profile JSON and optional written file paths.

    Raises:
        TypeError: If any profile argument has an unexpected type.
        OSError: If writing an artifact fails.
    """
    _validate_inputs(features, emotional_state, profile)

    why_lines = _why_this_look(emotional_state, profile)
    summary_md = _compose_summary_md(features, emotional_state, profile, repository_name, why_lines)
    profile_json = _serialize_profiles(features, emotional_state, profile)

    summary_path: Path | None = None
    profile_path: Path | None = None

    if output_dir is not None:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        summary_path = out / "summary.md"
        profile_path = out / "profile.json"
        summary_path.write_text(summary_md, encoding="utf-8")
        profile_path.write_text(profile_json, encoding="utf-8")

    return ExplanationArtifacts(
        summary_md=summary_md,
        why_this_look=why_lines,
        profile_json=profile_json,
        summary_path=summary_path,
        profile_path=profile_path,
    )
